#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  full_bin = "export $(cat .env | xargs) && ./tmp/main"
  delay = 1000
  entrypoint = ["./tmp/main"]
  exclude_dir = ["tmp"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  include_file = [".env"]
  include_ext = ["go", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
