name: CI

on:
  schedule:
    - cron: '0 6,12 * * *'

jobs:
  backend-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check profile tguerin
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://ftbadge.cc/profile/tguerin'
            method: 'GET'
            retry: '3'
            retryWait: '10'
